public class HtmlTemplates {

    public static String getWelcomePage() {
        return head("CineMatch — Bem-vindos")
            + baseStyles()
            + "<style>\n"
            + "body{display:flex;align-items:center;justify-content:center;min-height:100vh;}\n"
            + ".welcome{position:relative;z-index:1;text-align:center;padding:40px 24px;max-width:520px;width:100%;}\n"
            + ".brand-icon{width:56px;height:56px;background:var(--red);border-radius:16px;display:flex;align-items:center;justify-content:center;margin:0 auto 18px;}\n"
            + ".brand-icon i{font-size:28px;color:#fff;}\n"
            + ".brand-name{font-family:'Playfair Display',serif;font-size:2.6rem;color:#fff;letter-spacing:-0.5px;}\n"
            + ".brand-tagline{color:var(--subtle);font-size:0.85rem;margin-top:6px;letter-spacing:0.3px;}\n"
            + ".photos-row{display:flex;align-items:center;justify-content:center;gap:0;margin:36px auto;width:fit-content;}\n"
            + ".photo-frame{width:110px;height:110px;border-radius:50%;overflow:hidden;border:3px solid var(--s3);background:var(--s2);display:flex;align-items:center;justify-content:center;flex-shrink:0;}\n"
            + ".photo-frame img{width:100%;height:100%;object-fit:cover;}\n"
            + ".photo-frame i{font-size:40px;color:var(--s3);}\n"
            + ".photo-frame.pf1{border-color:var(--p1);box-shadow:0 0 0 4px var(--p1l);z-index:2;}\n"
            + ".photo-frame.pf2{border-color:var(--p2);box-shadow:0 0 0 4px var(--p2l);margin-left:-20px;z-index:1;}\n"
            + ".heart-badge{width:32px;height:32px;background:var(--red);border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 -6px;z-index:3;position:relative;box-shadow:0 0 0 3px var(--bg);}\n"
            + ".heart-badge i{font-size:15px;color:#fff;}\n"
            + ".desc-card{background:var(--s1);border:1px solid var(--border);border-radius:16px;padding:24px;margin-bottom:28px;text-align:left;}\n"
            + ".desc-title{font-family:'Playfair Display',serif;font-size:1.1rem;color:#fff;margin-bottom:10px;}\n"
            + ".desc-text{color:var(--subtle);font-size:0.84rem;line-height:1.65;}\n"
            + ".features{display:flex;flex-direction:column;gap:10px;margin-top:14px;}\n"
            + ".feat{display:flex;align-items:center;gap:10px;font-size:0.82rem;color:var(--subtle);}\n"
            + ".feat i{font-size:16px;color:var(--muted);flex-shrink:0;}\n"
            + ".btn-start{width:100%;padding:15px;border-radius:12px;border:none;background:linear-gradient(135deg,var(--p1),var(--p2));color:#fff;font-size:0.92rem;font-weight:600;font-family:'Inter',sans-serif;cursor:pointer;display:flex;align-items:center;justify-content:center;gap:9px;letter-spacing:0.2px;transition:all 0.2s;}\n"
            + ".btn-start:hover{opacity:0.88;transform:translateY(-2px);box-shadow:0 10px 28px rgba(180,100,200,0.3);}\n"
            + ".btn-start i{font-size:18px;}\n"
            + "</style></head><body>\n"
            + "<div class='glow glow-a'></div><div class='glow glow-b'></div>\n"
            + "<div class='welcome'>\n"
            + "  <div class='brand-icon'><i class='ph ph-film-slate'></i></div>\n"
            + "  <div class='brand-name'>CineMatch</div>\n"
            + "  <div class='brand-tagline'>Descubra a compatibilidade cinematografica do casal</div>\n"
            + "  <div class='photos-row'>\n"
            + "    <div class='photo-frame pf1'><img src='/img/IMG_1666.jpg' alt='Pessoa 1'></div>\n"
            + "    <div class='heart-badge'><i class='ph ph-heart-fill'></i></div>\n"
            + "    <div class='photo-frame pf2'><img src='/img/IMG_1668.jpg' alt='Pessoa 2'></div>\n"
            + "  </div>\n"
            + "  <div class='desc-card'>\n"
            + "    <div class='desc-title'>O que e o CineMatch?</div>\n"
            + "    <div class='desc-text'>Um quiz divertido para casais descobrirem o quanto combinam no cinema. Cada um escolhe seus generos favoritos e responde perguntas sobre habitos de assistir filmes.</div>\n"
            + "    <div class='features'>\n"
            + "      <div class='feat'><i class='ph ph-chart-pie'></i> Calcula sua porcentagem de compatibilidade</div>\n"
            + "      <div class='feat'><i class='ph ph-popcorn'></i> Recomenda filmes perfeitos para assistirem juntos</div>\n"
            + "      <div class='feat'><i class='ph ph-lock'></i> Sem cadastro, sem dados salvos — so diversao</div>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "  <button class='btn-start' onclick=\"location.href='/quiz'\"><i class='ph ph-play-circle'></i> Comecar o Quiz</button>\n"
            + "</div>\n"
            + "</body></html>";
    }


    private static String head(String title) {
        return "<!DOCTYPE html>\n"
            + "<html lang='pt-BR'>\n"
            + "<head>\n"
            + "<meta charset='UTF-8'>\n"
            + "<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
            + "<title>" + title + "</title>\n"
            + "<link rel='preconnect' href='https://fonts.googleapis.com'>\n"
            + "<link href='https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:wght@600;700&display=swap' rel='stylesheet'>\n"
            + "<script src='https://unpkg.com/@phosphor-icons/web@2.1.1/src/index.js'></script>\n";
    }

    private static String baseStyles() {
        return "<style>\n"
            + "*, *::before, *::after { margin:0; padding:0; box-sizing:border-box; }\n"
            + ":root {\n"
            + "  --red:#e50914; --gold:#f5c518;\n"
            + "  --bg:#080810; --s1:#0f0f1a; --s2:#16162a; --s3:#1e1e30;\n"
            + "  --border:rgba(255,255,255,0.06); --border-hover:rgba(255,255,255,0.14);\n"
            + "  --text:#f0f0f5; --muted:#5a5a78; --subtle:#8888aa;\n"
            + "  --p1:#7c6af7; --p1l:rgba(124,106,247,0.12); --p1b:rgba(124,106,247,0.25);\n"
            + "  --p2:#f76a8a; --p2l:rgba(247,106,138,0.12); --p2b:rgba(247,106,138,0.25);\n"
            + "}\n"
            + "html, body { height:100%; }\n"
            + "body { font-family:'Inter',sans-serif; background:var(--bg); color:var(--text); -webkit-font-smoothing:antialiased; }\n"
            + "::selection { background:var(--red); color:#fff; }\n"
            + "::-webkit-scrollbar { width:5px; }\n"
            + "::-webkit-scrollbar-track { background:var(--bg); }\n"
            + "::-webkit-scrollbar-thumb { background:var(--s3); border-radius:3px; }\n"
            + ".glow { position:fixed; border-radius:50%; filter:blur(130px); pointer-events:none; z-index:0; }\n"
            + ".glow-a { width:500px; height:500px; background:var(--p1); opacity:0.07; top:-150px; left:-150px; }\n"
            + ".glow-b { width:500px; height:500px; background:var(--p2); opacity:0.07; bottom:-150px; right:-150px; }\n"
            + "</style>\n";
    }

    // ── SVG icons ──────────────────────────────────────────────────────────────
    private static String icon(String name) {
        // Using Phosphor icon tag — rendered by the phosphor script
        return "<i class='ph ph-" + name + "'></i>";
    }

    public static String getQuizPageHtml() {
        return head("CineMatch")
            + baseStyles()
            + quizStyles()
            + "</head><body>\n"
            + "<div class='glow glow-a'></div><div class='glow glow-b'></div>\n"
            + "<div class='page'>\n"
            + quizContent()
            + "</div>\n"
            + quizScript()
            + "</body></html>";
    }

    private static String quizStyles() {
        return "<style>\n"
            + ".page { min-height:100vh; display:flex; flex-direction:column; align-items:center; justify-content:center; padding:32px 20px; position:relative; z-index:1; }\n"
            + ".brand { text-align:center; margin-bottom:44px; }\n"
            + ".brand-icon { width:52px; height:52px; background:var(--red); border-radius:14px; display:flex; align-items:center; justify-content:center; margin:0 auto 16px; }\n"
            + ".brand-icon i { font-size:26px; color:#fff; }\n"
            + ".brand-name { font-family:'Playfair Display',serif; font-size:2.4rem; color:#fff; letter-spacing:-0.5px; }\n"
            + ".brand-sub { color:var(--muted); font-size:0.82rem; margin-top:6px; letter-spacing:0.4px; }\n"
            + ".card { background:var(--s1); border:1px solid var(--border); border-radius:20px; padding:36px; width:100%; max-width:540px; position:relative; z-index:1; }\n"
            + ".prog-wrap { margin-bottom:32px; }\n"
            + ".prog-meta { display:flex; justify-content:space-between; align-items:center; margin-bottom:8px; }\n"
            + ".prog-label { font-size:0.7rem; font-weight:600; letter-spacing:1.5px; text-transform:uppercase; color:var(--muted); }\n"
            + ".prog-steps { font-size:0.7rem; color:var(--muted); }\n"
            + ".prog-track { height:2px; background:var(--s3); border-radius:2px; overflow:hidden; }\n"
            + ".prog-fill { height:100%; background:linear-gradient(90deg,var(--p1),var(--p2)); border-radius:2px; transition:width 0.5s cubic-bezier(.4,0,.2,1); }\n"
            + ".step { display:none; }\n"
            + ".step.active { display:block; animation:fadeUp 0.3s ease; }\n"
            + "@keyframes fadeUp { from{opacity:0;transform:translateY(12px)} to{opacity:1;transform:translateY(0)} }\n"
            + ".step-title { font-family:'Playfair Display',serif; font-size:1.55rem; color:#fff; margin-bottom:6px; }\n"
            + ".step-desc { color:var(--subtle); font-size:0.83rem; margin-bottom:28px; line-height:1.55; }\n"
            + ".field { margin-bottom:14px; }\n"
            + ".field-label { font-size:0.68rem; font-weight:600; letter-spacing:1.5px; text-transform:uppercase; color:var(--muted); margin-bottom:8px; display:flex; align-items:center; gap:6px; }\n"
            + ".field-label i { font-size:13px; }\n"
            + ".field-label.lp1 i { color:var(--p1); }\n"
            + ".field-label.lp2 i { color:var(--p2); }\n"
            + ".input { width:100%; padding:13px 16px; border-radius:10px; border:1.5px solid var(--border); background:var(--s2); color:#fff; font-size:0.92rem; font-family:'Inter',sans-serif; outline:none; transition:border-color 0.2s, box-shadow 0.2s; }\n"
            + ".input:focus { border-color:var(--border-hover); box-shadow:0 0 0 3px rgba(255,255,255,0.03); }\n"
            + ".input::placeholder { color:var(--muted); }\n"
            + ".sep { display:flex; align-items:center; gap:12px; margin:6px 0 14px; }\n"
            + ".sep-line { flex:1; height:1px; background:var(--border); }\n"
            + ".sep-text { font-size:0.7rem; color:var(--muted); letter-spacing:1px; }\n"
            + ".player-bar { display:flex; align-items:center; gap:12px; padding:12px 16px; border-radius:12px; margin-bottom:24px; }\n"
            + ".player-bar.bar-p1 { background:var(--p1l); border:1px solid rgba(124,106,247,0.3); }\n"
            + ".player-bar.bar-p2 { background:var(--p2l); border:1px solid rgba(247,106,138,0.3); }\n"
            + ".bar-av { width:38px; height:38px; border-radius:50%; display:flex; align-items:center; justify-content:center; font-weight:700; font-size:0.9rem; flex-shrink:0; }\n"
            + ".bar-p1 .bar-av { background:var(--p1); }\n"
            + ".bar-p2 .bar-av { background:var(--p2); }\n"
            + ".bar-info { flex:1; }\n"
            + ".bar-name { font-weight:600; font-size:0.92rem; color:#fff; }\n"
            + ".bar-hint { font-size:0.72rem; color:var(--subtle); margin-top:2px; }\n"
            + ".bar-dot { width:7px; height:7px; border-radius:50%; animation:blink 1.6s infinite; }\n"
            + ".bar-p1 .bar-dot { background:var(--p1); }\n"
            + ".bar-p2 .bar-dot { background:var(--p2); }\n"
            + "@keyframes blink { 0%,100%{opacity:1} 50%{opacity:0.2} }\n"
            + ".sel-hint { font-size:0.72rem; color:var(--muted); text-align:right; margin-bottom:10px; }\n"
            + ".genres-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:8px; margin-bottom:24px; }\n"
            + ".g-chip { padding:13px 8px; border-radius:12px; border:1.5px solid var(--border); background:var(--s2); color:var(--subtle); cursor:pointer; font-size:0.78rem; font-family:'Inter',sans-serif; text-align:center; transition:all 0.15s; user-select:none; }\n"
            + ".g-chip:hover { border-color:var(--border-hover); color:var(--text); }\n"
            + ".g-chip .g-icon { display:flex; justify-content:center; margin-bottom:5px; }\n"
            + ".g-chip .g-icon i { font-size:18px; }\n"
            + ".g-chip.sp1 { border-color:var(--p1); background:var(--p1l); color:#fff; }\n"
            + ".g-chip.sp1 .g-icon i { color:var(--p1); }\n"
            + ".g-chip.sp2 { border-color:var(--p2); background:var(--p2l); color:#fff; }\n"
            + ".g-chip.sp2 .g-icon i { color:var(--p2); }\n"
            + ".q-block { margin-bottom:20px; }\n"
            + ".q-text { font-size:0.88rem; font-weight:500; color:#ccc; margin-bottom:10px; display:flex; gap:8px; align-items:flex-start; }\n"
            + ".q-num { font-size:0.7rem; font-weight:700; color:var(--muted); background:var(--s3); border-radius:5px; padding:2px 7px; margin-top:1px; flex-shrink:0; }\n"
            + ".q-opts { display:flex; flex-direction:column; gap:7px; }\n"
            + ".q-opt { padding:11px 14px; border-radius:9px; border:1.5px solid var(--border); background:transparent; color:var(--subtle); cursor:pointer; font-size:0.83rem; font-family:'Inter',sans-serif; text-align:left; transition:all 0.15s; display:flex; align-items:center; gap:8px; }\n"
            + ".q-opt i { font-size:14px; opacity:0; transition:opacity 0.15s; }\n"
            + ".q-opt:hover { border-color:var(--border-hover); color:var(--text); }\n"
            + ".q-opt.op1 { border-color:var(--p1); background:var(--p1l); color:#fff; }\n"
            + ".q-opt.op1 i { opacity:1; color:var(--p1); }\n"
            + ".q-opt.op2 { border-color:var(--p2); background:var(--p2l); color:#fff; }\n"
            + ".q-opt.op2 i { opacity:1; color:var(--p2); }\n"
            + ".btn { width:100%; padding:14px; border-radius:11px; border:none; font-size:0.88rem; font-weight:600; font-family:'Inter',sans-serif; cursor:pointer; transition:all 0.2s; display:flex; align-items:center; justify-content:center; gap:8px; letter-spacing:0.2px; }\n"
            + ".btn i { font-size:16px; }\n"
            + ".btn-p1 { background:var(--p1); color:#fff; }\n"
            + ".btn-p1:hover { background:#6a58e0; transform:translateY(-1px); box-shadow:0 8px 20px rgba(124,106,247,0.3); }\n"
            + ".btn-p2 { background:var(--p2); color:#fff; }\n"
            + ".btn-p2:hover { background:#e0587a; transform:translateY(-1px); box-shadow:0 8px 20px rgba(247,106,138,0.3); }\n"
            + ".btn-grad { background:linear-gradient(135deg,var(--p1),var(--p2)); color:#fff; }\n"
            + ".btn-grad:hover { opacity:0.88; transform:translateY(-1px); box-shadow:0 8px 20px rgba(180,100,200,0.25); }\n"
            + ".mt { margin-top:24px; }\n"
            + ".modal-overlay{position:fixed;inset:0;background:rgba(8,8,16,0.92);backdrop-filter:blur(8px);display:none;align-items:center;justify-content:center;z-index:999;animation:fadeIn 0.3s ease;}\n"
            + ".modal-overlay.show{display:flex;}\n"
            + "@keyframes fadeIn{from{opacity:0}to{opacity:1}}\n"
            + ".modal-box{background:var(--s1);border:1px solid var(--border);border-radius:20px;padding:48px 36px;max-width:420px;width:90%;text-align:center;animation:scaleIn 0.4s cubic-bezier(.4,0,.2,1);}\n"
            + "@keyframes scaleIn{from{opacity:0;transform:scale(0.9)}to{opacity:1;transform:scale(1)}}\n"
            + ".modal-avatars{display:flex;align-items:center;justify-content:center;gap:16px;margin-bottom:32px;}\n"
            + ".modal-av{width:80px;height:80px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:2rem;font-weight:700;position:relative;}\n"
            + ".modal-av.loading{animation:pulse 1.5s ease-in-out infinite;}\n"
            + "@keyframes pulse{0%,100%{transform:scale(1);opacity:1}50%{transform:scale(1.08);opacity:0.85}}\n"
            + ".modal-av.mav1{background:var(--p1);box-shadow:0 0 0 4px var(--p1l);}\n"
            + ".modal-av.mav2{background:var(--p2);box-shadow:0 0 0 4px var(--p2l);}\n"
            + ".modal-heart{width:36px;height:36px;background:var(--red);border-radius:50%;display:flex;align-items:center;justify-content:center;box-shadow:0 0 0 3px var(--bg);animation:heartbeat 1.2s ease-in-out infinite;}\n"
            + "@keyframes heartbeat{0%,100%{transform:scale(1)}14%{transform:scale(1.15)}28%{transform:scale(1)}42%{transform:scale(1.15)}70%{transform:scale(1)}}\n"
            + ".modal-heart i{font-size:16px;color:#fff;}\n"
            + ".modal-title{font-family:'Playfair Display',serif;font-size:1.5rem;color:#fff;margin-bottom:8px;}\n"
            + ".modal-subtitle{color:var(--subtle);font-size:0.85rem;margin-bottom:28px;}\n"
            + ".modal-pct{font-family:'Playfair Display',serif;font-size:4.5rem;font-weight:700;background:linear-gradient(135deg,var(--p1),var(--p2));-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;line-height:1;margin-bottom:12px;opacity:0;transform:scale(0.5);transition:all 0.6s cubic-bezier(.4,0,.2,1);}\n"
            + ".modal-pct.reveal{opacity:1;transform:scale(1);}\n"
            + ".modal-msg{color:var(--text);font-size:1rem;font-weight:500;margin-bottom:24px;opacity:0;transition:opacity 0.4s ease 0.3s;}\n"
            + ".modal-msg.reveal{opacity:1;}\n"
            + ".modal-btn{padding:13px 28px;border-radius:10px;border:none;background:linear-gradient(135deg,var(--p1),var(--p2));color:#fff;font-size:0.88rem;font-weight:600;font-family:'Inter',sans-serif;cursor:pointer;transition:all 0.2s;opacity:0;transition:opacity 0.4s ease 0.5s;}\n"
            + ".modal-btn.reveal{opacity:1;}\n"
            + ".modal-btn:hover{opacity:0.88;transform:translateY(-1px);}\n"
            + "</style>\n";
    }

    private static String quizContent() {
        return "<div class='brand'>\n"
            + "  <div class='brand-icon'><i class='ph ph-film-slate'></i></div>\n"
            + "  <div class='brand-name'>CineMatch</div>\n"
            + "  <div class='brand-sub'>Compatibilidade cinematografica do casal</div>\n"
            + "</div>\n"
            + "<div class='card'>\n"
            + "  <div class='prog-wrap'>\n"
            + "    <div class='prog-meta'><span class='prog-label' id='prog-lbl'>Inicio</span><span class='prog-steps' id='prog-steps'>1 / 5</span></div>\n"
            + "    <div class='prog-track'><div class='prog-fill' id='prog' style='width:20%'></div></div>\n"
            + "  </div>\n"

            // S1 - Nomes
            + "  <div class='step active' id='s1'>\n"
            + "    <div class='step-title'>Quem vai jogar?</div>\n"
            + "    <div class='step-desc'>Digite os nomes do casal para comecar</div>\n"
            + "    <div class='field'>\n"
            + "      <div class='field-label lp1'><i class='ph ph-user-circle'></i> Pessoa 1</div>\n"
            + "      <input class='input' id='n1' type='text' placeholder='Nome da primeira pessoa'>\n"
            + "    </div>\n"
            + "    <div class='sep'><div class='sep-line'></div><span class='sep-text'>E</span><div class='sep-line'></div></div>\n"
            + "    <div class='field'>\n"
            + "      <div class='field-label lp2'><i class='ph ph-user-circle'></i> Pessoa 2</div>\n"
            + "      <input class='input' id='n2' type='text' placeholder='Nome da segunda pessoa'>\n"
            + "    </div>\n"
            + "    <button class='btn btn-grad mt' onclick='initNames()'>Comecar <i class='ph ph-arrow-right'></i></button>\n"
            + "  </div>\n"

            // S2 - Generos P1
            + "  <div class='step' id='s2'>\n"
            + "    <div class='player-bar bar-p1'><div class='bar-av' id='av1'>A</div><div class='bar-info'><div class='bar-name pname1'>Pessoa 1</div><div class='bar-hint'>Escolha seus generos favoritos</div></div><div class='bar-dot'></div></div>\n"
            + "    <div class='step-title'>Generos favoritos</div>\n"
            + "    <div class='step-desc'>Selecione ate 4 generos que voce mais curte</div>\n"
            + "    <div class='sel-hint' id='gg1c'>0 / 4 selecionados</div>\n"
            + "    <div class='genres-grid' id='gg1'></div>\n"
            + "    <button class='btn btn-p1' onclick='toQ1()'>Proximo <i class='ph ph-arrow-right'></i></button>\n"
            + "  </div>\n"

            // S3 - Perguntas P1
            + "  <div class='step' id='s3'>\n"
            + "    <div class='player-bar bar-p1'><div class='bar-av' id='av1b'>A</div><div class='bar-info'><div class='bar-name pname1'>Pessoa 1</div><div class='bar-hint'>Responda as perguntas abaixo</div></div><div class='bar-dot'></div></div>\n"
            + "    <div class='step-title'>Suas preferencias</div>\n"
            + "    <div class='step-desc'>Seja honesto — isso afeta a compatibilidade</div>\n"
            + "    <div id='qq1'></div>\n"
            + "    <button class='btn btn-p1 mt' onclick='toG2()'>Proximo <i class='ph ph-arrow-right'></i></button>\n"
            + "  </div>\n"

            // S4 - Generos P2
            + "  <div class='step' id='s4'>\n"
            + "    <div class='player-bar bar-p2'><div class='bar-av' id='av2'>B</div><div class='bar-info'><div class='bar-name pname2'>Pessoa 2</div><div class='bar-hint'>Escolha seus generos favoritos</div></div><div class='bar-dot'></div></div>\n"
            + "    <div class='step-title'>Generos favoritos</div>\n"
            + "    <div class='step-desc'>Selecione ate 4 generos que voce mais curte</div>\n"
            + "    <div class='sel-hint' id='gg2c'>0 / 4 selecionados</div>\n"
            + "    <div class='genres-grid' id='gg2'></div>\n"
            + "    <button class='btn btn-p2' onclick='toQ2()'>Proximo <i class='ph ph-arrow-right'></i></button>\n"
            + "  </div>\n"

            // S5 - Perguntas P2
            + "  <div class='step' id='s5'>\n"
            + "    <div class='player-bar bar-p2'><div class='bar-av' id='av2b'>B</div><div class='bar-info'><div class='bar-name pname2'>Pessoa 2</div><div class='bar-hint'>Ultima etapa — quase la!</div></div><div class='bar-dot'></div></div>\n"
            + "    <div class='step-title'>Suas preferencias</div>\n"
            + "    <div class='step-desc'>Responda com sinceridade</div>\n"
            + "    <div id='qq2'></div>\n"
            + "    <button class='btn btn-p2 mt' onclick='submit()'>Ver Resultado <i class='ph ph-sparkle'></i></button>\n"
            + "  </div>\n"

            + "</div>\n"
            + "<div class='modal-overlay' id='modal'>\n"
            + "  <div class='modal-box'>\n"
            + "    <div class='modal-avatars'>\n"
            + "      <div class='modal-av mav1 loading' id='mav1'>A</div>\n"
            + "      <div class='modal-heart'><i class='ph ph-heart-fill'></i></div>\n"
            + "      <div class='modal-av mav2 loading' id='mav2'>B</div>\n"
            + "    </div>\n"
            + "    <div class='modal-title' id='mtitle'>Calculando compatibilidade...</div>\n"
            + "    <div class='modal-subtitle' id='msub'>Analisando suas respostas</div>\n"
            + "    <div class='modal-pct' id='mpct'>0%</div>\n"
            + "    <div class='modal-msg' id='mmsg'></div>\n"
            + "    <button class='modal-btn' id='mbtn' onclick='goToResult()'>Ver Detalhes Completos</button>\n"
            + "  </div>\n"
            + "</div>\n";
    }

    private static String quizScript() {
        return "<script>\n"
            + "const GENRES=[\n"
            + "  {id:'28',  name:'Acao',           icon:'ph-sword'},\n"
            + "  {id:'35',  name:'Comedia',         icon:'ph-smiley'},\n"
            + "  {id:'18',  name:'Drama',           icon:'ph-mask-sad'},\n"
            + "  {id:'27',  name:'Terror',          icon:'ph-skull'},\n"
            + "  {id:'10749',name:'Romance',        icon:'ph-heart'},\n"
            + "  {id:'878', name:'Ficcao Cient.',   icon:'ph-rocket'},\n"
            + "  {id:'16',  name:'Animacao',        icon:'ph-paint-brush'},\n"
            + "  {id:'53',  name:'Suspense',        icon:'ph-eye'},\n"
            + "  {id:'12',  name:'Aventura',        icon:'ph-compass'},\n"
            + "  {id:'14',  name:'Fantasia',        icon:'ph-magic-wand'},\n"
            + "  {id:'80',  name:'Crime',           icon:'ph-handcuffs'},\n"
            + "  {id:'99',  name:'Documentario',    icon:'ph-camera-movie'}\n"
            + "];\n"
            + "const QUESTIONS=[\n"
            + "  {t:'Voce prefere finais de filme:',o:['Felizes e previsíveis','Tristes mas realistas','Surpreendentes','Abertos a interpretacao']},\n"
            + "  {t:'Durante um filme chato, voce:',o:['Assiste ate o fim','Pega o celular','Dorme','Sugere trocar']},\n"
            + "  {t:'Qual seu ritual perfeito de cinema?',o:['Pipoca e refrigerante','Comida de verdade','So petiscos','Nada, so o filme']},\n"
            + "  {t:'Voce e do time:',o:['Maratona (varios eps/filmes)','Um por vez e refletir','Depende do humor','Assisto enquanto faco outras coisas']},\n"
            + "  {t:'Filme dublado ou legendado?',o:['Sempre dublado','Sempre legendado','Depende do filme','Tanto faz']},\n"
            + "  {t:'Voce chora assistindo filme?',o:['Nunca','Raramente','Frequentemente','Sempre que e emocionante']},\n"
            + "  {t:'Prefere assistir filmes:',o:['Lancamentos/novidades','Classicos antigos','Cult/independentes','Sucessos de bilheteria']}\n"
            + "];\n"
            + "const PROG_LABELS=['Inicio','Generos','Perguntas','Generos','Perguntas'];\n"
            + "let sg1=[],sg2=[],a1={},a2={},n1='',n2='';\n"
            + "function setStep(s){\n"
            + "  document.getElementById('prog').style.width=(s/5*100)+'%';\n"
            + "  document.getElementById('prog-lbl').textContent=PROG_LABELS[s-1];\n"
            + "  document.getElementById('prog-steps').textContent=s+' / 5';\n"
            + "}\n"
            + "function show(id){document.querySelectorAll('.step').forEach(e=>e.classList.remove('active'));document.getElementById(id).classList.add('active');}\n"
            + "function initNames(){\n"
            + "  n1=document.getElementById('n1').value.trim()||'Pessoa 1';\n"
            + "  n2=document.getElementById('n2').value.trim()||'Pessoa 2';\n"
            + "  document.querySelectorAll('.pname1').forEach(e=>e.textContent=n1);\n"
            + "  document.querySelectorAll('.pname2').forEach(e=>e.textContent=n2);\n"
            + "  ['av1','av1b'].forEach(id=>document.getElementById(id).textContent=n1[0].toUpperCase());\n"
            + "  ['av2','av2b'].forEach(id=>document.getElementById(id).textContent=n2[0].toUpperCase());\n"
            + "  buildGenres('gg1',sg1,'sp1','gg1c');show('s2');setStep(2);\n"
            + "}\n"
            + "function buildGenres(cid,arr,cls,cntId){\n"
            + "  const g=document.getElementById(cid);g.innerHTML='';\n"
            + "  GENRES.forEach(x=>{\n"
            + "    const d=document.createElement('div');\n"
            + "    d.className='g-chip'+(arr.includes(x.id)?' '+cls:'');\n"
            + "    d.innerHTML='<div class=\"g-icon\"><i class=\"ph '+x.icon+'\"></i></div>'+x.name;\n"
            + "    d.onclick=()=>{\n"
            + "      if(arr.includes(x.id)){arr.splice(arr.indexOf(x.id),1);d.classList.remove(cls);}\n"
            + "      else if(arr.length<4){arr.push(x.id);d.classList.add(cls);}\n"
            + "      document.getElementById(cntId).textContent=arr.length+' / 4 selecionados';\n"
            + "    };\n"
            + "    g.appendChild(d);\n"
            + "  });\n"
            + "}\n"
            + "function buildQuestions(cid,cls){\n"
            + "  const c=document.getElementById(cid);c.innerHTML='';\n"
            + "  QUESTIONS.forEach((q,qi)=>{\n"
            + "    const b=document.createElement('div');b.className='q-block';\n"
            + "    const opts=q.o.map((o,oi)=>\n"
            + "      '<button class=\"q-opt\" onclick=\"selOpt(this,\\''+cid+'\\','+qi+',\\''+cls+'\\')\">' +\n"
            + "      '<i class=\"ph ph-check-circle\"></i>'+o+'</button>'\n"
            + "    ).join('');\n"
            + "    b.innerHTML='<div class=\"q-text\"><span class=\"q-num\">'+(qi+1)+'</span>'+q.t+'</div><div class=\"q-opts\">'+opts+'</div>';\n"
            + "    c.appendChild(b);\n"
            + "  });\n"
            + "}\n"
            + "function selOpt(btn,cid,qi,cls){\n"
            + "  btn.closest('.q-opts').querySelectorAll('.q-opt').forEach(b=>b.classList.remove('op1','op2'));\n"
            + "  btn.classList.add(cls==='sp1'?'op1':'op2');\n"
            + "}\n"
            + "function toQ1(){if(!sg1.length){alert('Selecione pelo menos 1 genero!');return;}buildQuestions('qq1','sp1');show('s3');setStep(3);}\n"
            + "function toG2(){buildGenres('gg2',sg2,'sp2','gg2c');show('s4');setStep(4);}\n"
            + "function toQ2(){if(!sg2.length){alert('Selecione pelo menos 1 genero!');return;}buildQuestions('qq2','sp2');show('s5');setStep(5);}\n"
            + "let resultUrl='';\n"
            + "function submit(){\n"
            + "  resultUrl='/result?p1='+encodeURIComponent(n1)+'&p2='+encodeURIComponent(n2)+'&g1='+sg1.join(',')+'&g2='+sg2.join(',');\n"
            + "  document.getElementById('mav1').textContent=n1[0].toUpperCase();\n"
            + "  document.getElementById('mav2').textContent=n2[0].toUpperCase();\n"
            + "  document.getElementById('modal').classList.add('show');\n"
            + "  setTimeout(()=>{\n"
            + "    fetch(resultUrl).then(r=>r.text()).then(html=>{\n"
            + "      const parser=new DOMParser();\n"
            + "      const doc=parser.parseFromString(html,'text/html');\n"
            + "      const pctText=doc.getElementById('cpct')?doc.getElementById('cpct').textContent:'75%';\n"
            + "      const pct=parseInt(pctText);\n"
            + "      const msg=pct>=80?'Voces sao feitos um para o outro!':pct>=60?'Otima combinacao cinematografica!':pct>=40?'Gostos diferentes, mas isso e bom!':'Opostos se atraem no cinema!';\n"
            + "      document.getElementById('mtitle').textContent='Compatibilidade Calculada!';\n"
            + "      document.getElementById('msub').textContent=n1+' & '+n2;\n"
            + "      document.querySelectorAll('.modal-av').forEach(e=>e.classList.remove('loading'));\n"
            + "      setTimeout(()=>{\n"
            + "        const pctEl=document.getElementById('mpct');\n"
            + "        pctEl.classList.add('reveal');\n"
            + "        let cur=0;\n"
            + "        const step=pct>50?2:1;\n"
            + "        const interval=setInterval(()=>{\n"
            + "          cur=Math.min(cur+step,pct);\n"
            + "          pctEl.textContent=cur+'%';\n"
            + "          if(cur>=pct)clearInterval(interval);\n"
            + "        },20);\n"
            + "        setTimeout(()=>{\n"
            + "          document.getElementById('mmsg').textContent=msg;\n"
            + "          document.getElementById('mmsg').classList.add('reveal');\n"
            + "          document.getElementById('mbtn').classList.add('reveal');\n"
            + "        },800);\n"
            + "      },300);\n"
            + "    });\n"
            + "  },1500);\n"
            + "}\n"
            + "function goToResult(){window.location.href=resultUrl;}\n"
            + "</script>\n";
    }

    public static String getResultPage(String p1, String p2, int compatibility, String moviesJson, String genres1, String genres2) {
        String compatMsg = compatibility >= 80 ? "Voces sao feitos um para o outro" :
                           compatibility >= 60 ? "Otima combinacao cinematografica" :
                           compatibility >= 40 ? "Gostos diferentes, mas isso e bom" :
                           "Opostos se atraem no cinema";
        String ringColor = compatibility >= 80 ? "#e50914" :
                           compatibility >= 60 ? "#f5c518" :
                           compatibility >= 40 ? "#22c55e" : "#7c6af7";
        String av1 = p1.length() > 0 ? String.valueOf(p1.charAt(0)).toUpperCase() : "A";
        String av2 = p2.length() > 0 ? String.valueOf(p2.charAt(0)).toUpperCase() : "B";

        return head("CineMatch — Resultado")
            + baseStyles()
            + "<style>\n"
            + ".glow-a{background:var(--p1);opacity:0.06;top:-150px;left:-150px;}\n"
            + ".glow-b{background:var(--p2);opacity:0.06;bottom:-150px;right:-150px;}\n"
            + ".hero{text-align:center;padding:56px 24px 40px;position:relative;z-index:1;}\n"
            + ".hero-brand{font-size:0.72rem;font-weight:600;letter-spacing:3px;text-transform:uppercase;color:var(--muted);margin-bottom:36px;display:flex;align-items:center;justify-content:center;gap:8px;}\n"
            + ".hero-brand i{font-size:14px;}\n"
            + ".players-row{display:flex;align-items:center;justify-content:center;gap:16px;margin-bottom:40px;flex-wrap:wrap;}\n"
            + ".p-pill{display:flex;align-items:center;gap:10px;padding:9px 18px;border-radius:50px;}\n"
            + ".p-pill.pp1{background:var(--p1l);border:1px solid rgba(124,106,247,0.3);}\n"
            + ".p-pill.pp2{background:var(--p2l);border:1px solid rgba(247,106,138,0.3);}\n"
            + ".p-av{width:34px;height:34px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:0.85rem;}\n"
            + ".pp1 .p-av{background:var(--p1);}\n"
            + ".pp2 .p-av{background:var(--p2);}\n"
            + ".p-name{font-weight:600;font-size:0.9rem;}\n"
            + ".vs{font-size:0.65rem;font-weight:700;letter-spacing:2px;color:var(--muted);}\n"
            + ".ring-wrap{position:relative;width:190px;height:190px;margin:0 auto 20px;}\n"
            + ".ring-wrap svg{transform:rotate(-90deg);}\n"
            + ".r-bg{fill:none;stroke:var(--s2);stroke-width:8;}\n"
            + ".r-fill{fill:none;stroke-width:8;stroke-linecap:round;stroke-dasharray:534;stroke-dashoffset:534;transition:stroke-dashoffset 1.6s cubic-bezier(.4,0,.2,1);}\n"
            + ".ring-center{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;}\n"
            + ".ring-pct{font-family:'Playfair Display',serif;font-size:3rem;font-weight:700;color:#fff;line-height:1;}\n"
            + ".ring-lbl{font-size:0.65rem;letter-spacing:2px;text-transform:uppercase;color:var(--muted);margin-top:4px;}\n"
            + ".compat-msg{font-size:1rem;color:var(--subtle);margin-top:10px;}\n"
            + ".content{max-width:980px;margin:0 auto;padding:0 24px 64px;position:relative;z-index:1;}\n"
            + ".sec{margin-bottom:48px;}\n"
            + ".sec-head{display:flex;align-items:center;gap:10px;margin-bottom:20px;padding-bottom:14px;border-bottom:1px solid var(--border);}\n"
            + ".sec-head i{font-size:18px;color:var(--muted);}\n"
            + ".sec-head span{font-family:'Playfair Display',serif;font-size:1.2rem;color:#fff;}\n"
            + ".genres-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;}\n"
            + ".g-panel{background:var(--s1);border:1px solid var(--border);border-radius:14px;padding:18px;}\n"
            + ".g-panel-head{display:flex;align-items:center;gap:9px;margin-bottom:12px;}\n"
            + ".g-pav{width:28px;height:28px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:0.75rem;font-weight:700;}\n"
            + ".gp1 .g-pav{background:var(--p1);}\n"
            + ".gp2 .g-pav{background:var(--p2);}\n"
            + ".g-pname{font-weight:600;font-size:0.85rem;}\n"
            + ".g-tag{display:inline-flex;align-items:center;gap:5px;border-radius:6px;padding:4px 10px;font-size:0.75rem;margin:3px;}\n"
            + ".g-tag i{font-size:12px;}\n"
            + ".gt1{background:var(--p1l);border:1px solid rgba(124,106,247,0.25);color:#a89ff7;}\n"
            + ".gt2{background:var(--p2l);border:1px solid rgba(247,106,138,0.25);color:#f7a0b5;}\n"
            + ".movies-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(175px,1fr));gap:14px;}\n"
            + ".mc{background:var(--s1);border:1px solid var(--border);border-radius:14px;overflow:hidden;transition:transform 0.2s,border-color 0.2s,box-shadow 0.2s;}\n"
            + ".mc:hover{transform:translateY(-4px);border-color:var(--border-hover);box-shadow:0 16px 40px rgba(0,0,0,0.5);}\n"
            + ".mc-img{width:100%;aspect-ratio:2/3;object-fit:cover;display:block;background:var(--s2);}\n"
            + ".mc-ph{width:100%;aspect-ratio:2/3;background:var(--s2);display:flex;align-items:center;justify-content:center;}\n"
            + ".mc-ph i{font-size:36px;color:var(--s3);}\n"
            + ".mc-body{padding:12px;}\n"
            + ".mc-title{font-size:0.82rem;font-weight:600;color:#eee;margin-bottom:5px;line-height:1.35;}\n"
            + ".mc-meta{font-size:0.72rem;color:var(--muted);line-height:1.6;}\n"
            + ".mc-rating{display:inline-flex;align-items:center;gap:4px;background:rgba(245,197,24,0.08);border:1px solid rgba(245,197,24,0.2);color:var(--gold);border-radius:5px;padding:2px 7px;font-size:0.72rem;font-weight:600;margin-top:7px;}\n"
            + ".mc-rating i{font-size:11px;}\n"
            + ".mc-tags{margin-top:5px;}\n"
            + ".mc-tag{display:inline-block;background:var(--s2);border-radius:5px;padding:2px 6px;font-size:0.68rem;color:var(--muted);margin:2px 2px 0 0;}\n"
            + ".btn-back{display:inline-flex;align-items:center;gap:8px;padding:11px 24px;border-radius:9px;border:1px solid var(--border);background:transparent;color:var(--subtle);font-size:0.82rem;font-family:'Inter',sans-serif;cursor:pointer;transition:all 0.2s;text-decoration:none;}\n"
            + ".btn-back:hover{border-color:var(--border-hover);color:var(--text);background:var(--s1);}\n"
            + ".btn-back i{font-size:15px;}\n"
            + ".center{text-align:center;padding-bottom:48px;position:relative;z-index:1;}\n"
            + ".spinner{width:32px;height:32px;border:2px solid var(--border);border-top-color:var(--red);border-radius:50%;animation:spin 0.8s linear infinite;margin:48px auto 12px;}\n"
            + "@keyframes spin{to{transform:rotate(360deg)}}\n"
            + ".load-txt{color:var(--muted);font-size:0.82rem;text-align:center;}\n"
            + "@media(max-width:600px){.genres-grid{grid-template-columns:1fr}.movies-grid{grid-template-columns:repeat(2,1fr)}.players-row{gap:10px}}\n"
            + "</style></head><body>\n"
            + "<div class='glow glow-a'></div><div class='glow glow-b'></div>\n"
            + "<div class='hero'>\n"
            + "  <div class='hero-brand'><i class='ph ph-film-slate'></i> CineMatch</div>\n"
            + "  <div class='players-row'>\n"
            + "    <div class='p-pill pp1'><div class='p-av'>" + av1 + "</div><span class='p-name'>" + p1 + "</span></div>\n"
            + "    <span class='vs'>VS</span>\n"
            + "    <div class='p-pill pp2'><div class='p-av'>" + av2 + "</div><span class='p-name'>" + p2 + "</span></div>\n"
            + "  </div>\n"
            + "  <div class='ring-wrap'>\n"
            + "    <svg width='190' height='190' viewBox='0 0 190 190'>\n"
            + "      <circle class='r-bg' cx='95' cy='95' r='85'/>\n"
            + "      <circle class='r-fill' id='ring' cx='95' cy='95' r='85' stroke='" + ringColor + "'/>\n"
            + "    </svg>\n"
            + "    <div class='ring-center'><div class='ring-pct' id='cpct'>0%</div><div class='ring-lbl'>compativeis</div></div>\n"
            + "  </div>\n"
            + "  <div class='compat-msg'>" + compatMsg + "</div>\n"
            + "</div>\n"
            + "<div class='content'>\n"
            + "  <div class='sec'>\n"
            + "    <div class='sec-head'><i class='ph ph-chart-bar'></i><span>Comparativo de Generos</span></div>\n"
            + "    <div class='genres-grid'>\n"
            + "      <div class='g-panel gp1'><div class='g-panel-head'><div class='g-pav'>" + av1 + "</div><span class='g-pname'>" + p1 + "</span></div><div id='gt1'></div></div>\n"
            + "      <div class='g-panel gp2'><div class='g-panel-head'><div class='g-pav'>" + av2 + "</div><span class='g-pname'>" + p2 + "</span></div><div id='gt2'></div></div>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "  <div class='sec'>\n"
            + "    <div class='sec-head'><i class='ph ph-popcorn'></i><span>Filmes Recomendados para Voces</span></div>\n"
            + "    <div id='movies'><div class='spinner'></div><div class='load-txt'>Buscando filmes...</div></div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "<div class='center'><a href='/' class='btn-back'><i class='ph ph-arrow-left'></i> Novo quiz</a></div>\n"
            + "<script>\n"
            + "const GM={'28':'Acao','35':'Comedia','18':'Drama','27':'Terror','10749':'Romance','878':'Ficcao Cient.','16':'Animacao','53':'Suspense','12':'Aventura','14':'Fantasia','80':'Crime','99':'Documentario'};\n"
            + "const GI={'28':'ph-sword','35':'ph-smiley','18':'ph-mask-sad','27':'ph-skull','10749':'ph-heart','878':'ph-rocket','16':'ph-paint-brush','53':'ph-eye','12':'ph-compass','14':'ph-magic-wand','80':'ph-handcuffs','99':'ph-camera-movie'};\n"
            + "const target=" + compatibility + ";\n"
            + "const g1='" + genres1 + "'.split(',').filter(Boolean);\n"
            + "const g2='" + genres2 + "'.split(',').filter(Boolean);\n"
            + "let cur=0;const iv=setInterval(()=>{cur=Math.min(cur+2,target);document.getElementById('cpct').textContent=cur+'%';if(cur>=target)clearInterval(iv);},25);\n"
            + "const circ=2*Math.PI*85;document.getElementById('ring').style.strokeDashoffset=circ-(circ*target/100);\n"
            + "function renderTags(ids,cid,cls){\n"
            + "  const el=document.getElementById(cid);\n"
            + "  el.innerHTML=ids.length?ids.map(id=>'<span class=\"g-tag '+cls+'\"><i class=\"ph '+(GI[id]||'ph-film')+'\"></i>'+(GM[id]||id)+'</span>').join(''):'<span style=\"color:var(--muted);font-size:0.8rem\">Nenhum selecionado</span>';\n"
            + "}\n"
            + "renderTags(g1,'gt1','gt1');renderTags(g2,'gt2','gt2');\n"
            + "const data=" + moviesJson + ";\n"
            + "const mc=document.getElementById('movies');\n"
            + "if(data.results&&data.results.length){\n"
            + "  mc.innerHTML='<div class=\"movies-grid\">'+data.results.slice(0,12).map(m=>{\n"
            + "    const img=m.poster_path?'<img class=\"mc-img\" src=\"https://image.tmdb.org/t/p/w300'+m.poster_path+'\" alt=\"\" loading=\"lazy\">':\n"
            + "      '<div class=\"mc-ph\"><i class=\"ph ph-film-strip\"></i></div>';\n"
            + "    const yr=m.release_date?m.release_date.slice(0,4):'—';\n"
            + "    const rt=m.vote_average?m.vote_average.toFixed(1):'—';\n"
            + "    const ov=m.overview?m.overview.slice(0,80)+'...':'Sem descricao disponivel.';\n"
            + "    const tgs=(m.genre_ids||[]).slice(0,2).map(id=>'<span class=\"mc-tag\">'+(GM[id]||'')+'</span>').join('');\n"
            + "    return '<div class=\"mc\">'+img+'<div class=\"mc-body\"><div class=\"mc-title\">'+m.title+'</div>'\n"
            + "      +'<div class=\"mc-meta\">'+yr+' &middot; '+(m.original_language||'').toUpperCase()+'<br><small>'+ov+'</small></div>'\n"
            + "      +'<div class=\"mc-tags\">'+tgs+'</div>'\n"
            + "      +'<div class=\"mc-rating\"><i class=\"ph ph-star-fill\"></i>'+rt+'</div></div></div>';\n"
            + "  }).join('')+'</div>';\n"
            + "}else{\n"
            + "  mc.innerHTML='<div class=\"load-txt\" style=\"padding:40px 0\">Nao foi possivel carregar filmes. Verifique sua conexao.</div>';\n"
            + "}\n"
            + "</script></body></html>";
    }
}
